{
    "id_": "51ecfe90-0a9c-4bbb-a64f-b2eba03bcb40",
    "embedding": None,
    "metadata": {
        "page_label": "1",
        "file_name": "MAHA_초기설정퀵가이드.pdf",
        "file_path": "C:\\kdw\\workspace\\chatbot\\data\\documents\\2025\\MAHA_초기설정퀵가이드.pdf",
        "file_type": "application/pdf",
        "file_size": 3299476,
        "creation_date": "2026-02-10",
        "last_modified_date": "2026-02-10",
    },
    "excluded_embed_metadata_keys": [
        "file_name",
        "file_type",
        "file_size",
        "creation_date",
        "last_modified_date",
        "last_accessed_date",
    ],
    "excluded_llm_metadata_keys": [
        "file_name",
        "file_type",
        "file_size",
        "creation_date",
        "last_modified_date",
        "last_accessed_date",
    ],
    "relationships": {},
    "metadata_template": "{key}: {value}",
    "metadata_separator": "\n",
    "text_resource": {
        "embeddings": None,
        "text": "유지보수전문기업을위한운영자동화플랫폼, 마하플랫\n마하플랫시작 가이드\n",
        "path": None,
        "url": None,
        "mimetype": None,
    },
    "image_resource": None,
    "audio_resource": None,
    "video_resource": None,
    "text_template": "{metadata_str}\n\n{content}",
    "class_name": "Document",
    "text": "유지보수전문기업을위한운영자동화플랫폼, 마하플랫\n마하플랫시작 가이드\n",
}
